// <auto-generated />
using System;
using ImunoMeta.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImunoMeta.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230503175138_VacinaData")]
    partial class VacinaData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("bit");

                    b.Property<string>("Use")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Use");

                    b.ToTable("Keys", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Key");

                    b.HasIndex("ConsumedTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataCadastroUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Removido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<Guid>("UsuarioContatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioContatoId1")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioId1")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioContatoId1");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Denuncia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataCadastroUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("Removido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("UrlDenunciada")
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioId1")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Denuncia");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataCadastroUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Removido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("UsuarioDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioDestinoId1")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioId1")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioDestinoId1");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Mensagem");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Noticia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataCadastroUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Removido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("UrlImagemCapa")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Noticia");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fb75976-7321-4578-b779-752f4b65f507"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Removido = false,
                            Resumo = "Nesta etapa, poderão receber o imunizante profissionais de saúde, trabalhadores do sistema prisional, pessoas com deficiência e população privada de liberdade",
                            Texto = "A Secretaria de Saúde do Distrito Federal inicia nesta quarta-feira (22) a imunização de profissionais de saúde, trabalhadores prisionais, população privada de liberdade e pessoas com deficiência permanente com a versão bivalente da vacina contra a covid-19. O imunizante estará disponível em mais de 90 locais com atendimento das 8h às 17h.",
                            Titulo = "DF inicia vacinação bivalente contra a covid-19 para novos grupos",
                            UrlImagemCapa = "https://www.saude.df.gov.br/image/journal/article?img_id=3019334"
                        },
                        new
                        {
                            Id = new Guid("53a83cad-7ff0-4e3e-a0cc-163dae4cce6c"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Removido = false,
                            Resumo = "Secretaria nomeia novos profissionais e abre leitos de UTI e de enfermaria pediátrica, além de capacitar equipes para atender ao público infantil",
                            Texto = "A chegada do outono e do inverno nos meses de março a junho ocasiona a propagação de vírus que causam doenças respiratórias, majoritariamente, entre as crianças – em especial naquelas de até dois anos de idade, cujo sistema imunológico não é tão fortalecido.",
                            Titulo = "Saúde reforça serviços de atendimento às crianças",
                            UrlImagemCapa = "https://www.saude.df.gov.br/image/journal/article?img_id=3019298"
                        },
                        new
                        {
                            Id = new Guid("c30a49a8-4c66-4b95-b63e-0c24e5b00fcb"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Removido = false,
                            Resumo = "Palestra em unidade de saúde de Sobradinho busca tornar o atendimento a vítimas mais empático e aprofundar temas sensíveis, como traumas e agressões sexuais",
                            Texto = "Atendimento ainda mais empático. Esse foi um dos objetivos da palestra Violência sexual e compreensão das reações das vítimas realizada nessa segunda-feira (20), no Hospital Regional de Sobradinho (HRS). A iniciativa visa capacitar a rede que atua no acolhimento de casos de violência, incluindo profissionais da saúde e servidores da rede-adjunta, como educação, órgãos da justiça e conselhos tutelares.",
                            Titulo = "Hospital capacita servidores para acolher pessoas em situação de violência",
                            UrlImagemCapa = "https://www.saude.df.gov.br/image/journal/article?img_id=3019264"
                        });
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.PontoVacinacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataCadastroUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("Removido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioId1")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("PontoVacinacao");

                    b.HasData(
                        new
                        {
                            Id = new Guid("057d4c17-c940-4e49-b4f7-f1b030f043a7"),
                            Cidade = "Brasília",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "QI 3",
                            Latitude = -15.725453043781098,
                            Longitude = -47.873853836999871,
                            Nome = "UBS 1 Lago Norte",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("804abaa7-5b45-4fe6-b1a9-878079f75d59"),
                            Cidade = "Brasília",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Vila Varjão Quadra 5 Conjunto A Lote 17",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 1 Varjão",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("8be7b68c-aa00-458c-bc26-efb6b9b920b0"),
                            Cidade = "Brasília",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "SGAN 905",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 1 Asa Norte",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("6d5be054-beee-41f5-8990-d8bb341c84e5"),
                            Cidade = "Brasília",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "EQN 114/115",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 2 Asa Norte",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("ed5fca6d-a6b8-4a10-a311-898d507d9715"),
                            Cidade = "Brasília",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Rua Piau – Acampamento Pacheco",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 3 Vila Planalto",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("3565a0a8-dddd-4d3e-9e81-fceaf0813aef"),
                            Cidade = "Brasília",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "QS 514/515 – W3 Sul ",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "Policlínica 514 Sul",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("7ff1b674-b849-4eb3-a3cf-97fcaee6930a"),
                            Cidade = "Brasília",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "SHCES 601 - Lote 01 - Cruzeiro Novo",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 1 Cruzeiro",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("32fa6133-07b6-4808-9b20-3c9eda200eb7"),
                            Cidade = "Brasília",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Setor Escolar Lote 04 - Cruzeiro Velho",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 2 Cruzeiro",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("939bd4f4-08d1-4ee8-a227-9d30b96ad2e5"),
                            Cidade = "Brasília",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "SHIS QI 21 – Área Especial/23 – AE LT E – Lago Sul",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "Policlínica do Lago Sul",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("73013701-dc2b-4508-9f4c-e8339d7ebdf4"),
                            Cidade = "Sobradinho",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Quadra 14 Área Especial 22/23",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 1 Sobradinho",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("011de263-2ea3-41f2-bbb9-62dfe88d1560"),
                            Cidade = "Sobradinho",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Quadra 3 Área Especial Conjuntos D/E",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 2 Sobradinho",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("daaa47cf-5cc2-466b-92a2-0618ff52b594"),
                            Cidade = "Sobradinho",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Área Especial – Novo Setor de Mansões Nova Colina",
                            Latitude = -47.75527347168611,
                            Longitude = -15.64796549335305,
                            Nome = "UBS 3 Sobradinho – Nova Colina",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("fc901dfc-55d2-4346-87e5-adafc8d82303"),
                            Cidade = "Sobradinho",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Área Especial 01, Lote 01, Associação de Moradores, Vila BASEVI",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 5 Sobradinho - Basevi",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("c74a0d3b-31bd-4375-a268-fece8b1ce935"),
                            Cidade = "Sobradinho",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "DF 001 KM 120 Rua 08 Chácara 187 Lago Oeste, Sobradinho",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 6 Sobradinho - Lago Oeste",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("76bc2488-a2e1-4f40-b59f-2ab7bcd1fffe"),
                            Cidade = "Sobradinho",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Rodovia DF 420, Complexo de Saúde, Setor de Mansões, ao lado da UPA Sobradinho",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 1 Sobradinho II",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("5c48e0b1-063a-446e-8a10-cc72a09b2cd4"),
                            Cidade = "Sobradinho",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Condomínio Vale dos Pinheiros, Quadra 45 A, Conjunto A, Lote 56, Sobradinho II",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 3 Sobradinho II",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("345660eb-3f29-4f6a-a730-97e42b8dc8e1"),
                            Cidade = "Sobradinho",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Condomínio Mini-Chácaras, QMS 16 Rua 14 Casa 01 – Sobradinho II",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 5 Sobradinho II",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("ab0d7f3e-8091-4169-b720-daee6e130c23"),
                            Cidade = "Sobradinho",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Condomínio Vale das Acácias, Quadra 12, Lote 01, Sobradinho II",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 6 Sobradinho II",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("4aa86664-5972-42f1-8491-2f18c58b6baf"),
                            Cidade = "Sobradinho",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Quadra 5, Área Especial A, nº 1. Vila Buritizinho",
                            Latitude = -47.828150520004122,
                            Longitude = -15.65127289695881,
                            Nome = "UBS 7 Sobradinho II – Vila Buritizinho",
                            Removido = false,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("f35080ac-2d01-4658-b658-bcafbcb0020c"),
                            Cidade = "Sobradinho",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "DF 150 Km 12 Quadra 10 Casa 14 ",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "UBS 1 Fercal",
                            Removido = false,
                            UF = "DF"
                        });
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Pontuacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataCadastroUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Removido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<Guid>("TipoPontuacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioId1")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TipoPontuacaoId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Pontuacao");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.TipoPontuacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataCadastroUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Removido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<short>("Valor")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("TipoPontuacao");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e508ba2e-d41f-44ef-a0b4-9783a17bfd6a"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Denuncia",
                            Removido = false,
                            Valor = (short)50
                        },
                        new
                        {
                            Id = new Guid("894f442d-07fc-4c36-99c7-3f74dfdd7db8"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Compartilhar",
                            Removido = false,
                            Valor = (short)25
                        },
                        new
                        {
                            Id = new Guid("33ba1010-adc4-4d57-822d-627acf7a9e08"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Vacinas",
                            Removido = false,
                            Valor = (short)10
                        });
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Trofeu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataCadastroUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Removido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.ToTable("Trofeu");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.UsuarioTrofeu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataCadastroUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Removido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<Guid>("TrofeuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioId1")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TrofeuId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("UsuarioTrofeu");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.UsuarioVacina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataCadastroUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Removido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioId1")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("VacinaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId1");

                    b.HasIndex("VacinaId");

                    b.ToTable("UsuarioVacina");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Vacina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CssClass")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataCadastroUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("Removido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vacina");

                    b.HasData(
                        new
                        {
                            Id = new Guid("605d534a-7a92-4eac-b02f-e47b50fb1126"),
                            CssClass = "bg-secondary",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A vacina BCG protege contra a tuberculose – doença contagiosa, provocada pela bactéria Mycobacterium tuberculosis. Foi criada em 1.921 por Léon Calmette e Alphonse Guérin, dando origem ao nome BCG.",
                            Nome = "BCG",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("82192a6b-8f8a-404e-b38a-52b2b7e9b17d"),
                            CssClass = "bg-info",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "É uma infecção causada pelo vírus A (HAV) da hepatite, também conhecida como “hepatite infecciosa”. Na maioria dos casos, a hepatite A é uma doença de caráter benigno, contudo o curso sintomático e a letalidade aumentam com a idade.",
                            Nome = "Hepatite A",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("1248fa30-5042-4049-8e72-fad3e152b7cf"),
                            CssClass = "bg-dark",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A hepatite B é uma doença que provoca mal-estar, febre, dor de cabeça, cansaço, dor no abdômen, náuseas e vômitos. Na sua forma mais grave, pode causar infecções e até tumores no fígado. A vacina que previne contra a hepatite B deve ser aplicada ainda nas primeiras horas após o nascimento, fornecendo uma proteção entre 80 e 100%. É aplicada com uma injeção e as doses de reforço estão presentes na vacina pentavalente, que também protege contra tétano, coqueluche, difteria e meningite, causada pela Haemophilus influenza tipo B.",
                            Nome = "Hepatite B",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("98866d5d-6aed-4419-b83b-47edde60d095"),
                            CssClass = "bg-warning",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A vacina pentavalente é a combinação de cinco vacinas individuais em uma. O objetivo é proteger as pessoas contra múltiplas doenças ao mesmo tempo. Desde 2012, o Programa Nacional de Imunizações (PNI), do Ministério da Saúde, oferta a vacina pentavalente na rotina do Calendário Nacional de Vacinação.",
                            Nome = "Penta (DTP/Hib/Hep. B)",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("fc3696ab-288f-4796-8760-e65b9b6cefaf"),
                            CssClass = "bg-danger",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "O Ministério da Saúde recomenda a vacinação de todas as crianças menores de cinco anos de acordo com o Calendário Nacional de Vacinação. A imunização com as doses recomendadas é fundamental para evitar o adoecimento, além de complicações e óbitos.",
                            Nome = "Pneumocócica 10 valente",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("609bb9e1-c085-49f6-9d9c-61b32fe031d3"),
                            CssClass = "bg-success",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A vacina é indicada para prevenir contra a poliomielite causada por vírus dos tipos 1, 2 e 3.",
                            Nome = "Vacina Inativada Poliomielite (VIP)",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("b95ef933-8714-49b2-bd50-696e4c439fab"),
                            CssClass = "bg-light border",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A vacina é indicada para prevenir contra a poliomielite causada por vírus dos tipos 1, 2 e 3.",
                            Nome = "Vacina Oral Poliomielite (VOP)",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("da2ca772-6611-40d6-8a72-d73894293bfa"),
                            CssClass = "bg-secondary",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "AO imunizante que previne contra o rotavírus humano é a vacina VRH/VORH. A aplicação acontece com uma gotinha na boca dos bebês, a partir da sexta semana de vida, para proteger contra infecções provocadas pelo rotavírus, como a diarreia, uma das principais causas de problemas estomacais nas crianças.",
                            Nome = "Vacina Rotavírus Humano (VRH)",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("270eb4ea-f727-40bf-9add-c1d914da5889"),
                            CssClass = "bg-secondary",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A vacina é composta pelo oligossacarídeo meningocócico C conjugado com a proteína CRM197 e não possui o micro-organismo causador da doença, o que a torna mais segura. É indicada para imunização ativa de crianças a partir de 2 meses de idade, adolescentes e adultos para a prevenção da doença invasiva causada por Neisseria meningitidis do sorogrupo C. Esta bactéria pode causar infecções graves, às vezes fatais, como a meningite e a sepse (infecção grave no sangue – infecção generalizada).",
                            Nome = "Meningocócica C (conjugada)",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("316d7af5-be61-4790-829a-60bbcdc1ed09"),
                            CssClass = "bg-warning",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "É uma doença de notificação compulsória imediata, ou seja, todo evento suspeito (tanto morte de primatas não humanos, quanto casos humanos com sintomatologia compatível) deve ser prontamente comunicado, em até 24 horas após a suspeita inicial, às autoridades locais competentes pela via mais rápida (telefone, fax, email, etc). Às autoridades estaduais de saúde cabe notificar os eventos de febre amarela suspeitos ao Ministério da Saúde. Atualmente, a febre amarela silvestre (FA) é uma doença endêmica no Brasil (região amazônica). ",
                            Nome = "Febre amarela",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("c50a9723-8e62-45af-9d29-9fbcbd94d6e9"),
                            CssClass = "bg-danger",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "No Sistema Único de Saúde (SUS), a vacina previne o sarampo, a caxumba e a rubéola. No Calendário Nacional de Vacinação, o imunizante está disponível para pessoas de 12 meses a 59 anos de idade, sendo recomendadas duas doses até 29 anos e uma dose de 30 a 59 anos, em pessoas não vacinadas. A vacinação é a forma mais eficaz de prevenção contra o sarampo e o objetivo é interromper a circulação do vírus e reduzir complicações e o número de óbitos pela doença.",
                            Nome = "Tríplice viral",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("f125c4a0-b01d-4cc7-8f46-b5682a1be921"),
                            CssClass = "bg-danger",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A vacina contra sarampo, caxumba, rubéola e varicela, também conhecida como tetra viral ou tetravalente viral é indicada para a vacinação de crianças com 15 meses de idade que já tenham recebido a primeira dose da vacina tríplice viral.",
                            Nome = "Tetraviral",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("a97d6bcc-a7d9-4dd9-b479-60b8e9e92f95"),
                            CssClass = "bg-secondary",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A vacina DTP (tríplice bacteriana), previne contra doenças como difteria, tétano e coqueluche, e é destinada a crianças entre 15 meses e quatro anos de idade como uma forma de reforço para as que já tenham se vacinado com a pentavalente.",
                            Nome = "DTP (tríplice bacteriana)",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("aaaf3e44-fee6-4ce0-8a50-e05ad0728d8d"),
                            CssClass = "bg-secondary",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A vacina contra sarampo, caxumba, rubéola e varicela, também conhecida como tetra viral ou tetravalente viral é indicada para a vacinação de crianças com 15 meses de idade que já tenham recebido a primeira dose da vacina tríplice viral.",
                            Nome = "Varicela",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("fcb93b24-3eee-40e4-b586-b350616f2afe"),
                            CssClass = "bg-dark text-white",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Segundo a Organização Mundial de Saúde (OMS), estima-se que haja de 9 a 10 milhões de infectados por esse vírus no Brasil e que a cada ano surjam 700 mil novos casos de infecção. O risco de desenvolvimento de cânceres associados ao HPV é cerca de quatro vezes maior entre pessoas vivendo com HIV/Aids e transplantados do que na população sem a doença ou transplante.",
                            Nome = "HPV quadrivalente",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("9beeb99b-99dc-4460-9e4d-08864199b4df"),
                            CssClass = "bg-primary",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Proteção contra o tétano acidental e a difteria.\r\nA difteriadifteriadifteriadifteriadifteria é causada por um bacilo, produtor de uma toxina\r\n(substância tóxica), que atinge as amídalas, a faringe, o nariz e a\r\npele, onde provoca placas branco-acinzentadas. É transmitida, por\r\nmeio de tosse ou espirro, de uma pessoa contaminada para outra.\r\nO tétanotétanotétanotétanotétano é uma infecção, causada por uma toxina (substância tóxica)\r\nproduzida pelo bacilo tetânico, que entra no organismo por meio de\r\nferimentos ou lesões na pele (tétano acidental) ou pelo coto do cordão\r\numbilical (tétano neonatal ou mal dos sete dias) e atinge o sistema\r\nnervoso central. Caracteriza-se por contrações e espasmos,\r\ndificuldade em engolir e rigidez no pescoço.",
                            Nome = "dT (dupla adulto)",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("f8ffd6bd-3a53-4e26-a05c-a1e4c9cac739"),
                            CssClass = "bg-info",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A vacina dTpa é uma associação de toxóide diftérico, toxóide tetânico e\r\ncomponentes purificados dos antígenos da Bordetella pertussis – toxina\r\npertussis, tendo o hidróxido e o fosfato de alumínio como adjuvante.",
                            Nome = "dTpa (DTP adulto)",
                            Removido = false
                        },
                        new
                        {
                            Id = new Guid("0f688e05-d401-42ac-a925-13eb218d70cb"),
                            CssClass = "bg-warning",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastroUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Previne as meningites e as doenças meningocócicas causadas pela bactéria meningococo dos tipos A, C, W e Y. Meningite meningocócica é uma forma grave de meningite bacteriana, altamente contagiosa, causada pela bactéria Neisseria meningitidis, também conhecida como meningococo.",
                            Nome = "dMenigocócica ACWY",
                            Removido = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Contato", b =>
                {
                    b.HasOne("ImunoMeta.Shared.Models.Usuario", "UsuarioContato")
                        .WithMany()
                        .HasForeignKey("UsuarioContatoId1");

                    b.HasOne("ImunoMeta.Shared.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioContato");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Denuncia", b =>
                {
                    b.HasOne("ImunoMeta.Shared.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Mensagem", b =>
                {
                    b.HasOne("ImunoMeta.Shared.Models.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("UsuarioDestinoId1");

                    b.HasOne("ImunoMeta.Shared.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioDestino");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.PontoVacinacao", b =>
                {
                    b.HasOne("ImunoMeta.Shared.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Pontuacao", b =>
                {
                    b.HasOne("ImunoMeta.Shared.Models.TipoPontuacao", "TipoPontuacao")
                        .WithMany()
                        .HasForeignKey("TipoPontuacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImunoMeta.Shared.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("TipoPontuacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.UsuarioTrofeu", b =>
                {
                    b.HasOne("ImunoMeta.Shared.Models.Trofeu", "Trofeu")
                        .WithMany()
                        .HasForeignKey("TrofeuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImunoMeta.Shared.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trofeu");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.UsuarioVacina", b =>
                {
                    b.HasOne("ImunoMeta.Shared.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImunoMeta.Shared.Models.Vacina", "Vacina")
                        .WithMany()
                        .HasForeignKey("VacinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vacina");
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Vacina", b =>
                {
                    b.HasOne("ImunoMeta.Shared.Models.Usuario", null)
                        .WithMany("Vacinas")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ImunoMeta.Shared.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ImunoMeta.Shared.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImunoMeta.Shared.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ImunoMeta.Shared.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImunoMeta.Shared.Models.Usuario", b =>
                {
                    b.Navigation("Vacinas");
                });
#pragma warning restore 612, 618
        }
    }
}
